name: Build
on:
  workflow_call:

jobs:
  build-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Install the project
        run: uv sync --locked --all-extras
        