name: Tests

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.16"
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        args: sync --locked --all-extras
    
    - name: Install dependencies
      run: uv sync --locked --all-extras 
      
    - name: Run pytest
      run: uv run pytest
